version: "2.1"

services:

  api:
    build: hexagonal-api/
    depends_on:
      db:
        condition: service_started
      dns:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    hostname: api

  db:
    image: postgres:12.1
    hostname: db

networks:
  default:
    driver: bridge